import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create CRUD Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen">
          <nav className="w-64 bg-gray-100 p-4 border-r">
            <h2 className="text-xl font-bold mb-4">My App</h2>
            <p className="text-gray-600 mb-4">
              This is a simple CRUD application using Next.js and TypeScript.
            </p>

            <ul className="space-y-2">
              <li>
                <Link href="/" className="text-blue-600 hover:underline">
                  Welcome
                </Link>
              </li>
              <li>
                <Link
                  href="/posts/list"
                  className="text-blue-600 hover:underline"
                >
                  List Post
                </Link>
              </li>
              <li>
                <Link href="/users" className="text-blue-600 hover:underline">
                  List User
                </Link>
              </li>
            </ul>
          </nav>

          <main className="flex-1 p-6 bg-gray-50">{children}</main>
        </div>
      </body>
    </html>
  );
}
